name: Tim Green
markdown: redcarpet
pygments: true

# Permalinks
permalink:	/blog/:title

# Setup
title: Tim Green - Le Blog
tagline: 'blog'
description: 'My personal blog.'
url: http://tiimgreen.com

icon: /assets/images/icon.png
cover: /assets/images/cover.jpg

author:
  name: 'Ian Camporez Brunelli'
  url: https://google.com/+IanCamporezBrunelli

paginate: 5

social:
  - icon: twitter
    url: https://twitter.com/tiimgreen
    desc: Follow me on twitter

  - icon: github
    url: https://github.com/tiimgreen
    desc: Fork me on github

menu:
  - title: Home
    url: /

  - title: About
    url: /about

copyright:
  author: Tim Green
  url: http://tiimgreen.com
  type_url: http://opensource.org/licenses/MIT
